name: DemoPytest

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run test cypress command line
        default: python -m pytest -v --tb=line tests/ --disable-warnings --html=report.html --title="Report QAE Test Demo" --self-contained-html

jobs:
  Execute-demoPytest:
    runs-on: ubuntu-latest
    steps:

    - name: Run pytest
      uses: pavelzw/pytest-action@v2
      with:
        verbose: true
        emoji: true
        job-summary: true
        custom-arguments: '-q'
        click-to-expand: true
        report-title: 'Report QAE Test Demo'

