name: DemoPytest

on:
  workflow_dispatch:
    inputs:
      cli:
        description: Run test cypress command line
        default: python -m pytest -v --tb=line tests/ --disable-warnings --html=report.html --title="Report QAE Test Demo" --self-contained-html

jobs:
  Execute-demoPytest:
    runs-on: ubuntu-latest
    steps:

      - name: Get Code
        uses: actions/checkout@v3.5.2
   
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Execute Teste
        run: python -m pytest -v --tb=line tests/ --disable-warnings --html=report.html --title="Report QAE Test Demo" --self-contained-html
      

        

